<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AcceptNPOIOSMFLicense>true</AcceptNPOIOSMFLicense>
    <DefaultItemExcludes>$(DefaultItemExcludes);tools\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="stuff\**\*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NPOI" Version="2.6.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
  </ItemGroup>

</Project>
